/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as AuthAllWorkoutsRouteImport } from './routes/_auth/allWorkouts'
import { Route as AuthActiveWorkoutRouteImport } from './routes/_auth/activeWorkout'
import { Route as AuthUserWorkoutAddNewRouteImport } from './routes/_auth/userWorkout/add-new'
import { Route as AuthUserWorkoutUserWorkoutIdRouteImport } from './routes/_auth/userWorkout/$userWorkoutId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAllWorkoutsRoute = AuthAllWorkoutsRouteImport.update({
  id: '/allWorkouts',
  path: '/allWorkouts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthActiveWorkoutRoute = AuthActiveWorkoutRouteImport.update({
  id: '/activeWorkout',
  path: '/activeWorkout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUserWorkoutAddNewRoute = AuthUserWorkoutAddNewRouteImport.update({
  id: '/userWorkout/add-new',
  path: '/userWorkout/add-new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUserWorkoutUserWorkoutIdRoute =
  AuthUserWorkoutUserWorkoutIdRouteImport.update({
    id: '/userWorkout/$userWorkoutId',
    path: '/userWorkout/$userWorkoutId',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activeWorkout': typeof AuthActiveWorkoutRoute
  '/allWorkouts': typeof AuthAllWorkoutsRoute
  '/test': typeof TestIndexRoute
  '/userWorkout/$userWorkoutId': typeof AuthUserWorkoutUserWorkoutIdRoute
  '/userWorkout/add-new': typeof AuthUserWorkoutAddNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activeWorkout': typeof AuthActiveWorkoutRoute
  '/allWorkouts': typeof AuthAllWorkoutsRoute
  '/test': typeof TestIndexRoute
  '/userWorkout/$userWorkoutId': typeof AuthUserWorkoutUserWorkoutIdRoute
  '/userWorkout/add-new': typeof AuthUserWorkoutAddNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/activeWorkout': typeof AuthActiveWorkoutRoute
  '/_auth/allWorkouts': typeof AuthAllWorkoutsRoute
  '/test/': typeof TestIndexRoute
  '/_auth/userWorkout/$userWorkoutId': typeof AuthUserWorkoutUserWorkoutIdRoute
  '/_auth/userWorkout/add-new': typeof AuthUserWorkoutAddNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activeWorkout'
    | '/allWorkouts'
    | '/test'
    | '/userWorkout/$userWorkoutId'
    | '/userWorkout/add-new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activeWorkout'
    | '/allWorkouts'
    | '/test'
    | '/userWorkout/$userWorkoutId'
    | '/userWorkout/add-new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/activeWorkout'
    | '/_auth/allWorkouts'
    | '/test/'
    | '/_auth/userWorkout/$userWorkoutId'
    | '/_auth/userWorkout/add-new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/allWorkouts': {
      id: '/_auth/allWorkouts'
      path: '/allWorkouts'
      fullPath: '/allWorkouts'
      preLoaderRoute: typeof AuthAllWorkoutsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/activeWorkout': {
      id: '/_auth/activeWorkout'
      path: '/activeWorkout'
      fullPath: '/activeWorkout'
      preLoaderRoute: typeof AuthActiveWorkoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/userWorkout/add-new': {
      id: '/_auth/userWorkout/add-new'
      path: '/userWorkout/add-new'
      fullPath: '/userWorkout/add-new'
      preLoaderRoute: typeof AuthUserWorkoutAddNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/userWorkout/$userWorkoutId': {
      id: '/_auth/userWorkout/$userWorkoutId'
      path: '/userWorkout/$userWorkoutId'
      fullPath: '/userWorkout/$userWorkoutId'
      preLoaderRoute: typeof AuthUserWorkoutUserWorkoutIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthActiveWorkoutRoute: typeof AuthActiveWorkoutRoute
  AuthAllWorkoutsRoute: typeof AuthAllWorkoutsRoute
  AuthUserWorkoutUserWorkoutIdRoute: typeof AuthUserWorkoutUserWorkoutIdRoute
  AuthUserWorkoutAddNewRoute: typeof AuthUserWorkoutAddNewRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthActiveWorkoutRoute: AuthActiveWorkoutRoute,
  AuthAllWorkoutsRoute: AuthAllWorkoutsRoute,
  AuthUserWorkoutUserWorkoutIdRoute: AuthUserWorkoutUserWorkoutIdRoute,
  AuthUserWorkoutAddNewRoute: AuthUserWorkoutAddNewRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
